#!/bin/bash

checkJava() {
    if ! which java > /dev/null 2>&1 || ! which javac > /dev/null 2>&1; then
        echo "It seems 'java' command isn't working properly. Please make sure everything is fine before continuing."
        exit 1
    fi
}

compile() {
    checkJava
    echo "Running compile"
    javac -cp ./ap.jar:. main.java

}

run() {
    checkJava
    
    java -cp ./ap.jar:. Fraquizz
    rm Fraquizz.class Region.class
}

if [[ "$1" == "compile" ]]; then
    compile
elif [[ "$1" == "run" ]]; then
    run
else
    compile
    run
fi